spring:
  application:
    name: LojadeProdutosDiversos 
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  # Corrigido de "anabled" para "enabled"
      path: /h2-console
